name: "Build and push to Patr"

on:
  workflow_dispatch:

jobs:
  Building:
      runs-on: ubuntu-latest
      name: "Build images"
      env:
        REGISTRY: registry.patr.cloud
        PATR_IMAGE: ${{ secrets.PATR_IMAGE }}
        PATR_USER: ${{ secrets.PATR_USER }}
        PATR_PASS: ${{ secrets.PATR_PASS }}

      steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to Patr Cloud
        uses: docker/login-action@v1.14.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.PATR_USER }}
          password: ${{ env.PATR_PASS }}

      - name: Build and push images to Patr Cloud
        uses: docker/build-push-action@v2.9.0
        with:
          push: true
          platforms: linux/amd64
          tags: ${{ env.PATR_IMAGE }}:test
